
title: SLAMid
description: Simultaneous Localization And Mapping (SLAM) and object identification.
show_downloads: false
google_analytics:
github_repository_url: https://github.com/SLAMid
github_is_project_page: true
github_repository_name: SLAMid Github Repo
email: slamid.rutgers@gmail.com
